= GServlet Developer Guide
Mamadou Lamine Ba <https://github.com/laminba2003[@laminba2003]>
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:description: This developer guide describes how to use the GServlet API.
:keywords: Java, Servlets, Groovy, reference, learn, how to
:doctype: book
:page-layout!:
:toc: left
:nofooter:
:sectanchors:
:sectlinks:
:sectnums:
:icons: font
:source-highlighter: highlightjs
:source-language: asciidoc

== Introduction to GServlet

GServlet is an open source project inspired from the http://docs.groovy-lang.org/latest/html/documentation/servlet-userguide.html[Groovlets], which aims to use the Groovy language and its provided modules to simplify Servlet API web development. Groovlets are Groovy scripts executed by a servlet. They are run on request, having the whole web context (request, response, etc.) bound to the evaluation context. They are much more suitable for smaller web applications. Compared to Java Servlets, coding in Groovy can be much simpler. It has a couple of implicit variables we can use, for example, _request_, _response_ to access the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[_HttpServletRequest_], and https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html[_HttpServletResponse_] objects. We have access to the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[_HttpSession_] with the _session_ variable. If we want to output data, we can use _out_, _sout_, and _html_.

.Groovlet.groovy 
[#src-listing] 
[source,java]  
----
if (!session) {
    session = request.getSession(true)
}
if (!session.counter) {
    session.counter = 1
}
html.html {
  head {
      title('Groovy Servlet')
  }
  body {
    p("Hello, ${request.remoteHost}: ${session.counter}! ${new Date()}")
  }
}
session.counter = session.counter + 1
----

The same philosophy has been followed in the design of this API and if you have no prior experience with the Groovy language, there are several curated lists of online resources for learning it.

* https://groovy-lang.org[Official Groovy Website]
* https://groovy-lang.org/learn.html#books[List of Programming Books]

== Main Features

* Servlet 3.1+ Support
* Groovy Scripting and Hot Reloading
* JSON, HTML and JDBC Support

== Requirements

* Java 7+
* Java IDE (Eclipse, IntelliJ IDEA, NetBeans..)
* Java EE 7+ compliant WebServer (Tomcat, Wildfly, Glassfish, Payara..)


== Installation

To get started with GServlet, you may want to begin by creating your first project. This section shows you how to get up and running quickly. It is highly recommended to consume the API through a dependency management tool and the artifact can be found in Maven's central repository. It is named **gservlet-api** and you just need to name a dependency on it in your project.

=== Maven

.pom.xml 
[#src-listing] 
[source,xml]  
---- 
<dependency>
	<groupId>org.gservlet</groupId>
	<artifactId>gservlet-api</artifactId>
	<version>1.0.0</version>
</dependency>
----

=== Gradle

.build.gradle 
[#src-listing] 
[source,java]  
---- 
repositories {
    mavenCentral()
}

dependencies {
    compile("org.gservlet:gservlet-api:1.0.0")
}
----

## Getting Started

Once your Java web server is installed and configured, you can put it to work. Five steps take you from writing your first Groovy servlet to running it. These steps are as follows:

. Create a dynamic web project
. Create the scripts folder inside your web content directory
. Write the servlet source code
. Run your Java web server
. Call your servlet from a web browser

You can find below some examples that you can try out. 
    
.ProjectServlet.java 
[#src-listing] 
[source,java]  
----
import org.gservlet.annotation.Servlet

@Servlet("/projects")
class ProjectServlet {

	def projects = []

	void init() {
	   projects << [id : 1, name : "Groovy", url : "https://groovy-lang.org"]
	   projects << [id : 2, name : "Spring", url : "https://spring.io"]
	   projects << [id : 3, name : "Maven",  url : "https://maven.apache.org"]
	}

	void get() {
	   json(projects)
	}

	void post() {
	   def project = request.body
	   projects << project
	   json(project)
	}

	void put() {
	   def project = request.body
	   int index = projects.findIndexOf { it.id == project.id }
	   projects[index] = project
	   json(project)
	}

	void delete() {
	   def project = request.body
	   int index = projects.findIndexOf { it.id == project.id }
	   json(projects.remove(index))
	}
	
}
----

.CorsFilter.java 
[#src-listing] 
[source,java]  
----
import org.gservlet.annotation.Filter

@Filter("/*")
class CorsFilter {

    void filter() {
      response.addHeader("Access-Control-Allow-Origin", "*")
      response.addHeader("Access-Control-Allow-Methods","GET, OPTIONS, HEAD, PUT, POST, DELETE")
      if (request.method == "OPTIONS") {
        response.status = response.SC_ACCEPTED
        return
      }
      next()
    }

}
----

.ServletRequestListener.java 
[#src-listing] 
[source,java]  
----
import org.gservlet.annotation.RequestListener

@RequestListener
class ServletRequestListener {

   void init() {
     println "request initialized"
   }

   void destroy() {
     println "request destroyed"
   }

}
----

For a hot reloading of your source code, set the **GSERVLET_RELOAD** environment variable to true in your IDE.

== Creating Servlets

A servlet is a small Java program that runs within a Web server. The https://docs.oracle.com/javaee/7/api/javax/servlet/Servlet.html[Servlet] interface defines methods that all servlets must implement. To implement this interface, you can write a generic servlet that extends the https://docs.oracle.com/javaee/7/api/javax/servlet/GenericServlet.html[GenericServlet] class or an HTTP servlet which extends the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html[HttpServlet] class and overrides at least one method, usually one of these:

* _doGet_, for HTTP GET requests
* _doPost_, for HTTP POST requests
* _doPut_, for HTTP PUT requests
* _doDelete_, for HTTP DELETE requests

This is a Java class that extends the HttpServlet class:

.MyHttpServlet.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet("/myServlet")
public class MyHttpServlet extends HttpServlet {
	
   public void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException {  
      response.setContentType("text/html");  
      PrintWriter out = response.getWriter();
      out.println("<html>");
      out.println("<body>");
      out.println("<p>Welcome to servlet</p>");
      out.println("</body>");
      out.println("</html>");  
   }
	
}
----

Now, we are going to write its Groovy counterpart with the GServlet API so you can perceive the difference in terms of simplicity and clarity. The name of the HTTP request method handlers are shortened to _get_, _post_ and so on. They take no arguments since the request and the response are now implicit variables.

.MyHttpServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet

@Servlet("/myServlet")
class MyHttpServlet {

   void get() {
      out.println("<html>")
      out.println("<body>")
      out.println("<p>Welcome to servlet</p>")
      out.println("</body>")
      out.println("</html>")     
   }
	
}
----

By default the Content-Type of the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html[HttpServletResponse] is set to _text/html_ and the implicit _out_ variable used to generate the HMTL content is nothing less than a reference to its https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#getWriter[PrintWriter] object. We could use as well the implicit _html_ variable which is an instance of a Groovy MarkupBuilder, to write a better version of this servlet.


.MyHttpServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet

@Servlet("/myServlet")
class MyHttpServlet {

  void get() {
     html.html {
       body {
         p("Welcome to gservlet")
       }
     } 
  }
   
}
----

The generated HTML content looks like this: 

.Generated HTML 
[#src-listing] 
[source,html]  
---- 
<!DOCTYPE html>
<html>
  <body>
    <p>Welcome to gservlet</p>
  </body>
</html>
----

=== Servlet implicit variables

The implicit variables made available to your servlets are as follows:

|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_config_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletConfig.html[ServletConfig] object

|_request_ |  https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[HttpServletRequest] object

|_response_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html)[HttpServletResponse] object
 
|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_sql_ | http://docs.groovy-lang.org/latest/html/api/groovy/sql/Sql.html[Sql] object

|_out_ | https://docs.oracle.com/javase/7/docs/api/java/io/PrintWriter.html[PrintWriter] object

|_html_ | http://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html[MarkupBuilder] object
|===


=== Servlet methods

|===
|Method |Description

|_void init()_ | handles the initialization process

|_void get()_ | handles the GET request

|_void post()_ | handles the POST request

|_void put()_ |  handles the PUT request

|_void delete()_ | handles the DELETE request
 
|_void head()_ | handles the HEAD request

|_void options()_ | handles the OPTIONS request

|_void trace()_ | handles the TRACE request.

|_void destroy()_ |  invoked when taken out of the service

|===


=== Servlet initialization parameters

Since Servlet 3, the https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/WebInitParam.html[@WebInitParam] annotation is used to specify initialization parameters for a servlet or filter programmatically, and it takes a required name and value. You can add a description but this is rather informative. In the initialization method _init()_, we can get our parameters using the _getInitParameter()_ method of the https://docs.oracle.com/javaee/7/api/javax/servlet/ServletConfig.html[ServletConfig] object. In the GServlet API, the annotation has been shorten to _@InitParam_ and you can get an initialization parameter through the implicit _config_ variable using just its name or as described above.

.UploadServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.InitParam
import org.gservlet.annotation.Servlet

@Servlet( urlPatterns = "/upload",
initParams = [
	@InitParam(name = "uploadDirectory", value = "/images")
] )
class UploadServlet {

	void init() {
		println config.uploadDirectory
		println config.getInitParameter("uploadDirectory")
	}

}
----

=== Servlet Multipart configuration

Supporting file uploads is a very basic and common requirement for many web applications. Prior to Servlet 3.0, implementing file upload required the use of external libraries or complex input processing. Version 3.0 of the Java Servlet specification helps to provide a viable solution to the problem in a generic and portable way. The Servlet 3.0 specification supports file upload out of the box, so any web container that implements the specification can parse multipart requests and make mime attachments available through the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[_HttpServletRequest_] object. A new annotation, https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/MultipartConfig.html[@MultipartConfig], is used to indicate that the servlet on which it is declared expects requests to made using the _multipart/form-data_ MIME type. Therefore, it can retrieve the Part components of a given _multipart/form-data_ request by calling the _getPart(String name)_ or _getParts()_ method of the https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[_HttpServletRequest_] object. In the GServlet API, the annotation has been shorten to _@Multipart_ while taking the same input parameters.

.UploadServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.InitParam
import org.gservlet.annotation.Servlet
import org.gservlet.annotation.Multipart

@Servlet( urlPatterns = "/upload",
initParams = [
	@InitParam(name = "uploadDirectory", value = "/images")
] )
@Multipart( fileSizeThreshold = 1024 * 1024, maxFileSize = 1024 * 1024 * 5, maxRequestSize = 1024 * 1024 * 25 )
class UploadServlet {

	String uploadPath

	void init() {
		uploadPath = context.getRealPath(config.uploadDirectory)
		File uploadDir = new File(uploadPath)
		if (!uploadDir.exists()) {
			uploadDir.mkdir()
		}
	}

	void post() {
		request.getParts().each { part ->
			String file = uploadPath + File.separator + getFileName(part)
			part.write(file)
		}
		json(["status" : 1])
	}

	String getFileName(part) {
		for(String content : part.getHeader("content-disposition").split(";")) {
			if ( content.trim().startsWith("filename")) {
				return content.substring( content.indexOf("=") + 2, content.length() - 1 )
			}
		}
		return "default.txt";
	}
}
----

=== Servlet Security

The https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/ServletSecurity.html[@ServletSecurity] annotation is used to specify security constraints on a Java servlet. The annotations https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/HttpMethodConstraint.html[@HttpMethodConstraint] and https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/HttpConstraint.html[@HttpConstraint] are used within that annotation to define the security constraints.

 
[#src-listing] 
[source,java]  
---- 
@ServletSecurity(
    httpMethodConstraints = <HttpMethodConstraint[]>,
    value = <HttpConstraint>
)
----

The _httpMethodConstraints_ attribute specifies one or more constraints for some specific HTTP methods, whereas the value attribute specifies a constraint that applies for all other HTTP methods.

.Encryption for all HTTP methods 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet
import javax.servlet.annotation.ServletSecurity
import javax.servlet.annotation.ServletSecurity.TransportGuarantee
import javax.servlet.annotation.HttpConstraint

@Servlet(value="/projects")
@ServletSecurity(@HttpConstraint(transportGuarantee = TransportGuarantee.CONFIDENTIAL))
class ProjectServlet {

	
}
----


.Denying access to HTTP POST method 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet
import javax.servlet.annotation.ServletSecurity
import javax.servlet.annotation.HttpMethodConstraint
import javax.servlet.annotation.ServletSecurity.EmptyRoleSemantic

@Servlet(value="/projects")
@ServletSecurity(httpMethodConstraints = @HttpMethodConstraint(value = "POST", 
	emptyRoleSemantic = EmptyRoleSemantic.DENY))
class ProjectServlet {

	
}
----


.Requiring that users must have the admin role 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet
import javax.servlet.annotation.ServletSecurity
import javax.servlet.annotation.HttpMethodConstraint

@Servlet(value="/projects")
@ServletSecurity(
 httpMethodConstraints = [
  @HttpMethodConstraint(value = "GET", rolesAllowed = "admin"),
  @HttpMethodConstraint(value = "POST", rolesAllowed = "admin"),      
 ]
)
class ProjectServlet {

	
}
----

You can find more examples about how to use the https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/ServletSecurity.html[@ServletSecurity] annotation on the web.

== Creating Filters

A filter is an object that performs filtering tasks on either the request to a resource (a servlet or static content), or on the response from a resource, or both. The https://docs.oracle.com/javaee/7/api/javax/servlet/Filter.html[Filter] interface defines methods that all filters must implement. Filters perform filtering in the _doFilter_ method.

This is a Java class that implements this interface:

.MyFilter.java 
[#src-listing] 
[source,java]  
----  
import javax.servlet.annotation.WebFilter;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.ServletException;
import java.io.IOException;
 
@WebFilter("/*")
public class MyFilter implements Filter {
 
    public void init(FilterConfig filterConfig) throws ServletException {  
    }
 
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {  
        chain.doFilter(request, response);
    }
 
    public void destroy() {
    }
    
}
----

The Groovy version of this filter with the GServlet API looks like this:

.MyFilter.groovy 
[#src-listing] 
[source,java]  
----  
import org.gservlet.annotation.Filter;
 
@Filter("/*")
class MyFilter {
 
    void init() {  
    }
 
    void filter() {
        next()
    }
 
    void destroy() {
    }
    
}
----

=== Filter implicit variables

The implicit variables made available to your filters are as follows:

|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_config_ | https://docs.oracle.com/javaee/7/api/javax/servlet/FilterConfig.html[FilterConfig] object

|_request_ |  https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[HttpServletRequest] object

|_response_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html)[HttpServletResponse] object

|_chain_ | https://docs.oracle.com/javaee/7/api/javax/servlet/FilterChain.html)[FilterChain] object
 
|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_sql_ | http://docs.groovy-lang.org/latest/html/api/groovy/sql/Sql.html[Sql] object

|_out_ | https://docs.oracle.com/javase/7/docs/api/java/io/PrintWriter.html[PrintWriter] object

|_html_ | http://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html[MarkupBuilder] object
|===

=== Filter methods

|===
|Method |Description

|_void init()_ | handles the initialization process

|_void filter()_ | handles the filtering tasks

|_void destroy()_ |  invoked when taken out of the service


|===


=== Filter initialization parameters

== Creating Listeners

During the lifetime of a typical Java EE web application, a number of events take place. The Servlet API provides a number of listener interfaces that we can implement to react to these events.

|=== 

| https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextListener.html[ServletContextListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] lifecycle changes.

| https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextAttributeListener.html[ServletContextAttributeListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] attribute changes.

| https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestListener.html[ServletRequestListener] | Interface for receiving notification events about a https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html[ServletRequest] coming into and going out of scope of a web application.

| https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestAttributeListener.html[ServletRequestAttributeListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html[ServletRequest] attribute changes.

| https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionListener.html[HttpSessionListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] lifecycle changes.

| https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionAttributeListener.html[HttpSessionAttributeListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] attribute changes.

| https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionBindingListener.html[HttpSessionBindingListener] | Interface for receiving notification events when an object is bound to or unbound from a https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession].


| https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionActivationListener.html[HttpSessionActivationListener] | Interface for receiving notification events when an https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] is being passivated and and activated.


| https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionIdListener.html[HttpSessionIdListener] | Interface for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] id changes.

|=== 

=== ServletContextListener

This interface is for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] lifecycle changes. Implementations of this interface are invoked at their https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextListener.html#contextInitialized-javax.servlet.ServletContextEvent[contextInitialized] method in the order in which they have been declared, and at their https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextListener.html#contextDestroyed-javax.servlet.ServletContextEvent-[contextDestroyed] method in reverse order.

.MyServletContextListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletContextListener implements ServletContextListener {
	
	public void contextInitialized(ServletContextEvent event) {
	   System.out.println("context started");	
	}
	
	public void contextDestroyed(ServletContextEvent event) {
	   System.out.println("context destroyed");
	}
	
}
----


.MyServletContextListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.ContextListener

@ContextListener
public class MyServletContextListener {
	
	void contextInitialized() {
	   println "context started"	
	}
	
	void contextDestroyed() {
	   println "context destroyed"
	}
	
}
----

The implicit variables made available to your ServletContext listeners are as follows:

.ServletContextListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextEvent.html[ServletContextEvent] object
|===

=== ServletContextAttributeListener

This interface is for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] attribute changes. The order in which implementations of this interface are invoked is unspecified.

.MyServletContextAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletContextAttributeEvent;
import javax.servlet.ServletContextAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletContextAttributeListener implements ServletContextAttributeListener {

    public void attributeAdded(ServletContextAttributeEvent event) {
        System.out.println("attr " + event.getName() + " added with value " + event.getValue());
    }

    public void attributeRemoved(ServletContextAttributeEvent event) {
        System.out.println("attr " + event.getName() + " removed with value " + event.getValue());
    }

    public void attributeReplaced(ServletContextAttributeEvent event) {
        System.out.println("attr " + event.getName() + " replaced with value " + event.getValue());
    }
    
}
----

.MyServletContextAttributeListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.ContextAttributeListener

@ContextAttributeListener
public class MyServletContextAttributeListener {

    void attributeAdded() {
        println "attr $name added with value $value"
    }

    void attributeRemoved() {
        println "attr $name removed with value $value"
    }

    void attributeReplaced() {
        println "attr $name replaced with value $value"
    }
    
}
----

The implicit variables made available to your ServletContext attribute listeners are as follows:

.ServletContextAttributeListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextAttributeEvent.html[ServletContextAttributeEvent] object

|_name_ | attribute name

|_value_ | attribute value
|===

=== ServletRequestListener

This interface is for receiving notification events about requests coming into and going out of scope of a web application. A request is defined as coming into scope of a web application when it is about to enter the first servlet or filter of the web application, and as going out of scope as it exits the last servlet or the first filter in the chain. Implementations of this interface are invoked at their https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestListener.html#requestInitialized-javax.servlet.ServletRequestEvent[requestInitialized] method in the order in which they have been declared, and at their https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestListener.html#requestDestroyed-javax.servlet.ServletRequestEvent-[requestDestroyed] method in reverse order.

.MyServletRequestListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletRequestEvent;
import javax.servlet.ServletRequestListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletRequestListener implements ServletRequestListener {

    public void requestInitialized(ServletRequestEvent event) {
        System.out.println("request initialized");
    }

    public void requestDestroyed(ServletRequestEvent event) {
        System.out.println("request destroyed");
    }
    
}
----

.MyServletRequestListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.RequestListener

@RequestListener
public class MyServletRequestListener {

    void requestInitialized() {
        println "request initialized"
    }

    void requestDestroyed() {
        println "request destroyed"
    }
    
}
----

The implicit variables made available to your ServletRequest listeners are as follows:

.ServletRequestListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_request_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[HttpServletRequest] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestEvent.html[ServletRequestEvent] object

|===

=== ServletRequestAttributeListener

This interface is for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html[ServletRequest] attribute changes.
Notifications will be generated while the request is within the scope of the web application. A ServletRequest is defined as coming into scope of a web application when it is about to enter the first servlet or filter of the web application, and as going out of scope when it exits the last servlet or the first filter in the chain. The order in which implementations of this interface are invoked is unspecified.

.MyServletRequestAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletRequestAttributeEvent;
import javax.servlet.ServletRequestAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletRequestAttributeListener implements ServletRequestAttributeListener {

    public void attributeAdded(ServletRequestAttributeEvent event) {
        System.out.println("attr " + event.getName() + " added with value " + event.getValue());
    }

    public void attributeRemoved(ServletRequestAttributeEvent event) {
        System.out.println("attr " + event.getName() + " removed with value " + event.getValue());
    }

    public void attributeReplaced(ServletRequestAttributeEvent event) {
        System.out.println("attr " + event.getName() + " replaced with value " + event.getValue());
    }
    
}
----

.MyServletRequestAttributeListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.RequestAttributeListener

@RequestAttributeListener
public class MyServletRequestAttributeListener {

    void attributeAdded() {
        println "attr $name added with value $value"
    }

    void attributeRemoved() {
        println "attr $name removed with value $value"
    }

    void attributeReplaced() {
        println "attr $name replaced with value $value"
    }
    
}
----

The implicit variables made available to your ServletRequest attribute listeners are as follows:

.ServletRequestAttributeListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_request_ |  https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html[HttpServletRequest] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_context_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html[ServletContext] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestAttributeEvent.html[ServletRequestAttributeEvent] object

|_name_ | attribute name

|_value_ | attribute value
|===

=== HttpSessionListener

This interface is for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] lifecycle changes. Implementations of this interface are invoked at their https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionListener.html#sessionCreated-javax.servlet.http.HttpSessionEvent[sessionCreated] method in the order in which they have been declared, and at their https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionListener.html#sessionDestroyed-javax.servlet.http.HttpSessionEvent[sessionDestroyed] method in reverse order.


.MyHttpSessionListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionEvent;
import javax.servlet.HttpSessionListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionListener implements HttpSessionListener {
	
	public void sessionCreated(HttpSessionEvent event) {
	  System.out.println("session created");	
	}
	
	public void sessionDestroyed(HttpSessionEvent event) {
	  System.out.println("session destroyed");
	}
	
}
----

.MyHttpSessionListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.SessionListener

@SessionListener
public class MyHttpSessionListener {
	
	void sessionCreated() {
	   println "session created"	
	}
	
	void sessionDestroyed() {
	   println "session destroyed"
	}
	
}
----

The implicit variables made available to your HttpSession listeners are as follows:

.HttpSessionListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionEvent.html[HttpSessionEvent] object

|===


=== HttpSessionAttributeListener

This interface is for receiving notification events about https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] attribute changes. The order in which implementations of this interface are invoked is unspecified.


.MyHttpSessionAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionBindingEvent;
import javax.servlet.HttpSessionAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionAttributeListener implements HttpSessionAttributeListener {

    public void attributeAdded(HttpSessionBindingEvent event) {
        System.out.println("attr " + event.getName() + " added with value " + event.getValue());
    }

    public void attributeRemoved(HttpSessionBindingEvent event) {
        System.out.println("attr " + event.getName() + " removed with value " + event.getValue());
    }

    public void attributeReplaced(HttpSessionBindingEvent event) {
        System.out.println("attr " + event.getName() + " replaced with value " + event.getValue());
    }
    
}
----


.MyHttpSessionAttributeListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.SessionAttributeListener

@SessionAttributeListener
public class MyHttpSessionAttributeListener {

    void attributeAdded() {
        println "attr $name added with value $value"
    }

    void attributeRemoved() {
        println "attr $name removed with value $value"
    }

    void attributeReplaced() {
        println "attr $name replaced with value $value"
    }
    
}
----

The implicit variables made available to your HttpSession attribute listeners are as follows:

.HttpSessionAttributeListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_event_ |  https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionBindingEvent.html[HttpSessionBindingEvent] object

|_name_ | attribute name

|_value_ | attribute value
|===

=== HttpSessionBindingListener

This interface is for receiving notification events about when an object is bound to or unbound from a session. This may be as a result of a servlet programmer explicitly unbinding an attribute from a session, due to a session being invalidated, or due to a session timing out.

.MyHttpSessionBindingListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionBindingEvent;
import javax.servlet.http.HttpSessionBindingListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionBindingListener implements HttpSessionBindingListener {

    public void valueBound(HttpSessionBindingEvent event) {
        System.out.println("attr " + event.getName() + " bounded with value " + event.getValue());
    }

    public void valueUnbound(HttpSessionBindingEvent event) {
        System.out.println("attr " + event.getName() + " unbounded with value " + event.getValue());
    }
    
}
----

.MyHttpSessionBindingListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.SessionBindingListener

@SessionBindingListener
public class MyHttpSessionBindingListener {

    void valueBound() {
        println "attr $name bounded with value $value"
    }

    void valueUnbound() {
        println "attr $name unbounded with value $value"
    }
    
}
----

The implicit variables made available to your HttpSession binding listeners are as follows:

.HttpSessionBindingListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_event_ |  https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionBindingEvent.html[HttpSessionBindingEvent] object

|_name_ | attribute name

|_value_ | attribute value
|===

=== HttpSessionActivationListener

Objects that are bound to a session may listen to container events notifying them that sessions will be passivated and activated. A container that migrates session between VMs or persists sessions is required to notify all attributes bound to sessions implementing this interface.

.MyHttpSessionActivationListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionActivationListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionActivationListener implements HttpSessionActivationListener {

    public void sessionDidActivate(HttpSessionEvent event) {
        System.out.println("session activated");
    }

    public void sessionWillPassivate(HttpSessionEvent event) {
        System.out.println("session passivated");
    }
    
}
----

.MyHttpSessionActivationListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.SessionActivationListener

@SessionActivationListener
public class MyHttpSessionActivationListener {

    void sessionDidActivate() {
        println "session activated"
    }

    void sessionWillPassivate() {
        println "session passivated"
    }
    
}
----

The implicit variables made available to your HttpSession activation listeners are as follows:

.HttpSessionActivationListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionEvent.html[HttpSessionEvent] object

|===

=== HttpSessionIdListener

This interface is for receiving notification events about HttpSession id changes. The order in which implementations of this interface are invoked is unspecified.

.MyHttpSessionIdListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionIdListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionIdListener implements HttpSessionIdListener {

    public void sessionIdChanged(HttpSessionEvent event, String oldSessionId) {
        System.out.println("the session id was "+oldSessionId);
    }
    
}
----

.MyHttpSessionIdListener.groovy 
[#src-listing] 
[source,java]  
---- 
import org.servlet.annotation.SessionIdListenerThe implicit variables below are made available

@WebListener
public class MyHttpSessionIdListener {

    void sessionIdChanged() {
        println "the session id was $oldSessionId"
    }
    
}
----

The implicit variables made available to your HttpSession Id listeners are as follows:

.HttpSessionIdListener Implicit Variables
|===
|Variable |Description

|_logger_ | https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html[logger] object

|_session_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] object

|_event_ | https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionEvent.html[HttpSessionEvent] object

|_oldSessionId_ | old https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html[HttpSession] Id

|===

== Working With JSON

Groovy comes with integrated support for converting between Groovy objects and JSON. The classes dedicated to JSON serialisation and parsing are found in the *_groovy.json_* package. You can get an insight of how to use them in the Groovy https://groovy-lang.org/json.html[documentation]. In the Gservlet API, we have simplified the process of parsing and producing JSON in your servlets and filters as below: 

.CustomerServlet.java 
[#src-listing] 
[source,java]  
----
import org.gservlet.annotation.Servlet

@Servlet("/projects")
class ProjectServlet {
   
   def projects = []

   void init() {
     projects << [id : 1, name : "Groovy", url : "https://groovy-lang.org"]
     projects << [id : 2, name : "Spring", url : "https://spring.io"]
     projects << [id : 3, name : "Maven",  url : "https://maven.apache.org"]
   }

   void get() {
     json(projects)
   }

   void post() {
     def project = request.body
     projects << project
     json(project)
   }
	
}
----

Whenever, the content-type of the request is set to *_application/json_*, you can use its *_body_* property to get the payload as Groovy object. Your servlet or filter can use as well the built-in *_json()_* method to send json data as a response.

== Working With RDBMS

The *_groovy-sql_* module provides a higher-level abstraction over the current Java’s JDBC technology and it supports a wide variety of databases. To set up a database with the GServlet API is as simple as to create in the root directory of your web application, a file named *_application.properties_* like below :

.application.properties 
[#src-listing] 
[source,plain]  
---- 
db.driver : oracle.jdbc.driver.OracleDriver
db.url : jdbc:oracle:thin:@10.0.0.85:1521:ssv8acs
db.user : ACSQA
db.password : acs
db.minPoolSize : 5
db.maxPoolSize : 10
----

For each request, an http://docs.groovy-lang.org/latest/html/api/groovy/sql/Sql.html[Sql] connection is automatically created from a data source and made available in your servlets and filters through the implicit _sql_ variable as below:

.ProjectServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet

@Servlet("/myServlet")
class ProjectServlet {
	
   void post() {
     def params = [1, 'Groovy', 'https://groovy-lang.org']
     sql.execute 'insert into projects (id, name, url) values (?, ?, ?)', params   
   }
	
}
----

.ProjectFilter.groovy 
[#src-listing] 
[source,java]  
----  
import org.gservlet.annotation.Filter;
 
@Filter("/*")
class ProjectFilter {
 
   void filter() {
      sql.eachRow('select * from projects') { project ->
         println "${project.name.padRight(10)} ($project.url)"
      }
      next()
   }
     
}
----

After each request, the _close()_ method of the http://docs.groovy-lang.org/latest/html/api/groovy/sql/Sql.html[Sql] object is automatically invoked to bring it back to the connection pool.    

== Copyright and License

Copyright @2020. Free use of this software is granted under the terms of the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0] License.

== Authors

GServlet was created by https://github.com/laminba2003[Mamadou Lamine Ba].

== Contributing

Contributions of any type or any scope, drive the project forward. There are lot of ways to contribute, not just code. We provide more information about how to get involved in our link:/contribute[contribute] page.
