= GServlet User Manual
Mamadou Lamine Ba <https://github.com/laminba2003[@laminba2003]>
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:description: This guide describes how to use the GServlet API.
:keywords: Java, Servlets, Groovy, reference, learn, how to
:doctype: book
:page-layout!:
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:icons: font
:source-highlighter: highlightjs
:source-language: asciidoc

== Installation

To get started with GServlet, you may want to begin by creating your first project. This section shows you how to get up and running quickly. It is highly recommended to consume the GServlet API through a dependency management tool and the artifact can be found in Maven's central repository. It is named **gservlet-api** and you just need to name a dependency on it in your project.

=== From Maven

.pom.xml 
[#src-listing] 
[source,xml]  
---- 
<dependency>
	<groupId>org.gservlet</groupId>
	<artifactId>gservlet-api</artifactId>
	<version>1.0.0</version>
</dependency>
----

=== From Gradle

.build.gradle 
[#src-listing] 
[source,java]  
---- 
repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.gservlet:gservlet-api:1.0.0'
}
----

== Creating Servlets

A servlet is a small Java program that runs within a Web server. The https://javaee.github.io/javaee-spec/javadocs/javax/servlet/Servlet.html[Servlet] interface defines methods that all servlets must implement. To implement this interface, you can write a generic servlet that extends the https://javaee.github.io/javaee-spec/javadocs/javax/servlet/GenericServlet.html[GenericServlet] class or an HTTP servlet which extends the https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServlet.html[HttpServlet] class and which overrides at least one method, usually one of these:

* _doGet_, for HTTP GET requests
* _doPost_, for HTTP POST requests
* _doPut_, for HTTP PUT requests
* _doDelete_, for HTTP DELETE requests

In the example below, we are going to create a Java servlet which extends the https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServlet.html[HttpServlet] class and which provides an implementation of the _doGet()_ method.


.MyHttpServlet.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet("/myServlet")
public class MyHttpServlet extends HttpServlet {
	
	@Override
	public void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException {  
	  response.setContentType("text/html");  
	  PrintWriter out = response.getWriter();
	  out.println("<html>");
	  out.println("<body>");
	  out.println("<p>Welcome to servlet</p>");
	  out.println("</body>");
	  out.println("</html>");  
   }
	
}
----

We are going now to write its Groovy counterpart with the GServlet API so you can perceive the difference in terms of simplicity and clarity. The name of the HTTP request method handlers are shortened to _get_, _post_ and so on. They take no arguments since the request and the response are implicit variables.


.MyHttpServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet

@Servlet("/myServlet")
class MyHttpServlet {
	
	void get() {
	  out.println("<html>")
	  out.println("<body>")
	  out.println("<p>Welcome to servlet</p>")
	  out.println("</body>")
	  out.println("</html>")     
   }
	
}
----

By default the Content-Type of the https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html[HttpServletResponse] is set to _text/html_ and the implicit _out_ variable used to generate the HMTL content is nothing less than a reference to its https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletResponse.html#getWriter[PrintWriter] object. We could use as well the implicit _html_ variable to write a better version of this servlet. It is nothing less than an instance of a Groovy MarkupBuilder bound to the response writer.


.MyHttpServlet.groovy 
[#src-listing] 
[source,java]  
---- 
import org.gservlet.annotation.Servlet

@Servlet("/myServlet")
class MyHttpServlet {
	
	void get() {
     html.html {
       body {
         p("Welcome to servlet")
       }
     } 
   }
   
}
----

The generated HTML content looks like this: 



.Generated HTML 
[#src-listing] 
[source,html]  
---- 
<!DOCTYPE html>
<html>
  <body>
    <p>Welcome to servlet</p>
  </body>
</html>
----

== Creating Filters

A filter is an object that performs filtering tasks on either the request to a resource (a servlet or static content), or on the response from a resource, or both. The https://javaee.github.io/javaee-spec/javadocs/javax/servlet/Filter.html[Filter] interface defines methods that all filters must implement. Filters perform filtering in the _doFilter_ method.

This is how to create a Java filter that implements this interface:

.MyFilter.java 
[#src-listing] 
[source,java]  
----  
import javax.servlet.annotation.WebFilter;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.ServletException;
import java.io.IOException;
 
@WebFilter("/*")
public class MyFilter implements Filter {
 
    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        // invoked when an instance of this filter is created  
    }
 
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {  
        // invoked for a matching request
        chain.doFilter(request, response);
    }
 
    @Override
    public void destroy() {
        // invoked when an instance of this filter is destroyed
    }
}
----

This is how to write a Filter with Groovy and the GServlet API:

.MyFilter.groovy 
[#src-listing] 
[source,java]  
----  
import org.gservlet.annotation.Filter;
 
@Filter("/*")
class MyFilter {
 
    void init() {
        // invoked when an instance of this filter is created  
    }
 
    void filter() {
        // invoked for a matching request
        next()
    }
 
    void destroy() {
        // invoked when an instance of this filter is destroyed
    }
}
----


== Creating Listeners

During the lifetime of a typical Java EE web application, a number of events take place. The Servlet API provides a number of listener interfaces that we can implement to react to these events.

|=== 

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContextListener.html[ServletContextListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html[ServletContext] lifecycle changes.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContextAttributeListener.html[ServletContextAttributeListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html[ServletContext] attribute changes.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequestListener.html[ServletRequestListener] | Interface for receiving notification events about a https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html[ServletRequest] coming into and going out of scope of a web application.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequestAttributeListener.html[ServletRequestAttributeListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html[ServletRequest] attribute changes.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionListener.html[HttpSessionListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] lifecycle changes.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionAttributeListener.html[HttpSessionAttributeListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] attribute changes.

| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionBindingListener.html[HttpSessionBindingListener] | Interface for receiving notification events when an object is bound to or unbound from a https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession].


| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionActivationListener.html[HttpSessionActivationListener] | Interface for receiving notification events when an https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] is being passivated and and activated.


| https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionIdListener.html[HttpSessionIdListener] | Interface for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] id changes.



|=== 

=== ServletContextListener

This interface is for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html[ServletContext] lifecycle changes. Implementations of this interface are invoked at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContextListener.html#contextInitialized-javax.servlet.ServletContextEvent[contextInitialized] method in the order in which they have been declared, and at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContextListener.html#contextDestroyed-javax.servlet.ServletContextEvent-[contextDestroyed] method in reverse order.

.MyServletContextListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletContextListener implements ServletContextListener {
	
	@Override
	public void contextInitialized(ServletContextEvent event) {
		System.out.println("context started");	
	}
	
	@Override
	public void contextDestroyed(ServletContextEvent event) {
		System.out.println("context destroyed");
	}
	
}
----


=== ServletContextAttributeListener

This interface is for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html[ServletContext] attribute changes. The order in which implementations of this interface are invoked is unspecified.

.MyServletContextAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletContextAttributeEvent;
import javax.servlet.ServletContextAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletContextAttributeListener implements ServletContextAttributeListener {

    @Override
    public void attributeAdded(ServletContextAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " added with value: " + event.getValue());
    }

    @Override
    public void attributeRemoved(ServletContextAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " removed with value: " + event.getValue());
    }

    @Override
    public void attributeReplaced(ServletContextAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " replaced with value: " + event.getValue());
    }
    
}
----


=== ServletRequestListener

This interface is for receiving notification events about requests coming into and going out of scope of a web application. A ServletRequest is defined as coming into scope of a web application when it is about to enter the first servlet or filter of the web application, and as going out of scope as it exits the last servlet or the first filter in the chain. Implementations of this interface are invoked at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequestListener.html#requestInitialized-javax.servlet.ServletRequestEvent[requestInitialized] method in the order in which they have been declared, and at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequestListener.html#requestDestroyed-javax.servlet.ServletRequestEvent-[requestDestroyed] method in reverse order.

.MyServletRequestListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletRequestEvent;
import javax.servlet.ServletRequestListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletRequestListener implements ServletRequestListener {

    @Override
    public void requestInitialized(ServletRequestEvent event) {
        System.out.println("request initialized");
    }

    @Override
    public void requestDestroyed(ServletRequestEvent event) {
        System.out.println("request destroyed");
    }
    
}
----


=== ServletRequestAttributeListener

This interface is for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html[ServletRequest] attribute changes.
Notifications will be generated while the request is within the scope of the web application. A ServletRequest is defined as coming into scope of a web application when it is about to enter the first servlet or filter of the web application, and as going out of scope when it exits the last servlet or the first filter in the chain. The order in which implementations of this interface are invoked is unspecified.

.MyServletRequestAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.ServletRequestAttributeEvent;
import javax.servlet.ServletRequestAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyServletRequestAttributeListener implements ServletRequestAttributeListener {

    @Override
    public void attributeAdded(ServletRequestAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " added with value: " + event.getValue());
    }

    @Override
    public void attributeRemoved(ServletRequestAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " removed with value: " + event.getValue());
    }

    @Override
    public void attributeReplaced(ServletRequestAttributeEvent event) {
        System.out.println("attr : " + event.getName() + " replaced with value: " + event.getValue());
    }
    
}
----


=== HttpSessionListener

This interface is for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] lifecycle changes. Implementations of this interface are invoked at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionListener.html#sessionCreated-javax.servlet.http.HttpSessionEvent[sessionCreated] method in the order in which they have been declared, and at their https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSessionListener.html#sessionDestroyed-javax.servlet.http.HttpSessionEvent[sessionDestroyed] method in reverse order.


.MyHttpSessionListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionEvent;
import javax.servlet.HttpSessionListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionListener implements HttpSessionListener {
	
	@Override
	public void sessionCreated(HttpSessionEvent event) {
		System.out.println("session created");	
	}
	
	@Override
	public void sessionDestroyed(HttpSessionEvent event) {
		System.out.println("session destroyed");
	}
	
}
----

=== HttpSessionAttributeListener

This interface is for receiving notification events about https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html[HttpSession] attribute changes. The order in which implementations of this interface are invoked is unspecified.


.MyHttpSessionAttributeListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionBindingEvent;
import javax.servlet.HttpSessionAttributeListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionAttributeListener implements HttpSessionAttributeListener {

    @Override
    public void attributeAdded(HttpSessionBindingEvent event) {
        System.out.println("attr : " + event.getName() + " added with value: " + event.getValue());
    }

    @Override
    public void attributeRemoved(HttpSessionBindingEvent event) {
        System.out.println("attr : " + event.getName() + " removed with value: " + event.getValue());
    }

    @Override
    public void attributeReplaced(HttpSessionBindingEvent event) {
        System.out.println("attr : " + event.getName() + " replaced with value: " + event.getValue());
    }
    
}
----

=== HttpSessionBindingListener

It causes an object to be notified when it is bound to or unbound from a session. This may be as a result of a servlet programmer explicitly unbinding an attribute from a session, due to a session being invalidated, or due to a session timing out.

.MyHttpSessionBindingListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.HttpSessionBindingEvent;
import javax.servlet.http.HttpSessionBindingListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionBindingListener implements HttpSessionBindingListener {

    @Override
    public void valueBound(HttpSessionBindingEvent event) {
        System.out.println("attr : " + event.getName() + " bounded with value: " + event.getValue());
    }

    @Override
    public void valueUnbound(HttpSessionBindingEvent event) {
        System.out.println("attr : " + event.getName() + " unbounded with value: " + event.getValue());
    }
    
}
----


=== HttpSessionActivationListener

Objects that are bound to a session may listen to container events notifying them that sessions will be passivated and activated. A container that migrates session between VMs or persists sessions is required to notify all attributes bound to sessions implementing this interface.

.MyHttpSessionActivationListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionActivationListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionActivationListener implements HttpSessionActivationListener {

    @Override
    public void sessionDidActivate(HttpSessionEvent event) {
        System.out.println("session activated");
    }

    @Override
    public void sessionWillPassivate(HttpSessionEvent event) {
        System.out.println("session passivated");
    }
    
}
----


=== HttpSessionIdListener

This interface is for receiving notification events about HttpSession id changes. The order in which implementations of this interface are invoked is unspecified.

.MyHttpSessionIdListener.java 
[#src-listing] 
[source,java]  
---- 
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionIdListener;
import javax.servlet.annotation.WebListener;

@WebListener
public class MyHttpSessionIdListener implements HttpSessionIdListener {

    @Override
    public void sessionIdChanged(HttpSessionEvent event, String oldSessionId) {
        System.out.println("session id changed");
    }
    
}
----

== Parsing and Producing JSON
== Working With a Database
== Servlets Examples
== Filters Examples
== Listeners Examples
== Copyright and License

Copyright @2019. Free use of this software is granted under the terms of the Apache 2.0 License.

See the https://www.apache.org/licenses/LICENSE-2.0[LICENSE] page for details.

== Authors

GServlet was written by https://github.com/laminba2003[Mamadou Lamine Ba].


== Contributing

GServlet is an open source project and contributions, of any type or any scope, drive the project forward. There are lot of ways to contribute, not just writing/fixing code.