language: java
branches:
  only:
    - develop
    - master
git:
  depth: false
env:
  - GSERVLET_RELOAD=true
addons:
  sonarcloud:
    organization: "gservlet"
    token:
      secure: "42a67c1071034211e878342993938110a39723e9"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GServlet_gservlet-api
after_success:
  - mvn clean test jacoco:report coveralls:report
