language: java
branches:
  only:
    - develop
    - master
git:
  depth: false
env:
  - GSERVLET_RELOAD=true
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "gservlet"
    token: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=GServlet_gservlet-api -Pcoverage
after_success:
  - mvn clean verify coveralls:report -Pcoverage
